data_provider:
  # root: /home/hpc/iwi5/iwi5361h/tiny-face-training-main/algorithm/dataset
  root : E:\Tiny-Training\algorithm\dataset\human
  num_classes: 50
  image_size: 112
  verification_targets_dir: /home/hpc/iwi5/iwi5361h/tiny-face-training-main/algorithm/eval_dataset
  verification_targets:
  - agedb_30
  - calfw
  - cfp_ff
  - cfp_fp
  - cplfw
  - lfw
  - vgg2_fp
  eval_image_size: [112,112]

run_config:
  # learning rate
  bs256_lr: 0.01
  # optimizer
  optimizer_name: sgd

net_config:
  net_name: mbv2-w0.35
  embedding_dim: 128
