backward_config:
  enable_backward_config: 1
  freeze_fc: 0
  manual_weight_idx: 27-30-33-36-39-42-45-48
  n_bias_update: 25
  n_weight_update: null
  pw1_weight_only: 0
  quantize_gradient: 0
  train_scale: 0
  weight_select_criteria: magnitude+
  weight_update_ratio: 1-1-1-1-1-0.125-0.5-1
data_provider:
  base_batch_size: 128
  color_aug: 0.4
  dataset_type: triplet
  eval_image_size:
  - 112
  - 112
  image_size: 112
  k_images: 4
  n_worker: 8
  num_classes: 10050
  p_identities: 32
  resize_scale: 0.08
  root: /home/hpc/iwi5/iwi5361h/tiny-face-training-main/algorithm/dataset
  verification_targets:
  - agedb_30
  - calfw
  - cfp_ff
  - cfp_fp
  - cplfw
  - lfw
  - vgg2_fp
  verification_targets_dir: /home/hpc/iwi5/iwi5361h/tiny-face-training-main/algorithm/eval_dataset
evaluate: false
manual_seed: 0
net_config:
  cls_head: linear
  dropout: 0.0
  embedding_dim: 128
  mcu_head_type: fp
  net_name: mbv2-w0.35
  pretrained: false
ray_tune: 0
resume: 0
run_config:
  base_lr: 0.025
  bias_only: 0
  bs256_lr: 0.1
  eval_per_epochs: 1
  fc_lr10: 0
  fc_only: 0
  grid_ckpt_path: null
  grid_output: null
  lr_schedule_name: cosine
  n_block_update: -1
  n_epochs: 10
  no_wd_keys:
  - norm
  - bias
  optimizer_name: sgd_scale_nomom
  warmup_epochs: 0
  warmup_lr: 0
  weight_decay: 0.0005
run_dir: runs-128/syn/mbv2-w0.35/sparse_100kb/sgd_qas_nomom
